import 'dotenv/config';
import { prisma } from '../lib/db';

async function main() {
  console.log('🚀 Bắt đầu quá trình nhập dữ liệu sản phẩm Pantum...');

  // 1. Upsert Thương hiệu Pantum
  const brand = await prisma.brand.upsert({
    where: { slug: 'pantum' },
    update: {
      name: 'Pantum',
      description: 'Thương hiệu máy in laser và giải pháp vật tư in ấn chính hãng Pantum.',
      isPartner: true,
    },
    create: {
      name: 'Pantum',
      slug: 'pantum',
      description: 'Thương hiệu máy in laser và giải pháp vật tư in ấn chính hãng Pantum.',
      isPartner: true,
      isActive: true,
    },
  });

  console.log(`✅ Thương hiệu Pantum (ID: ${brand.id}) sẵn sàng.`);

  // ID của danh mục gốc
  const CATEGORY_MAY_IN = 50;
  const CATEGORY_VAT_TU = 51;

  const defaultPrinterImage = 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500&h=500&fit=crop';
  const defaultSupplyImage = 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=500&h=500&fit=crop';

  const productsData = [
    // --------------------------------------------------------------------------
    // MÁY IN LASER ĐEN TRẮNG (Danh mục: Máy in - ID 50)
    // --------------------------------------------------------------------------
    {
      name: 'Máy in Laser Pantum P2505',
      slug: 'may-in-laser-pantum-p2505',
      sku: 'PANTUM-P2505',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in Laser đen trắng Pantum P2505 đơn năng, nhỏ gọn, tốc độ in 22 trang/phút, đáp ứng hoàn hảo nhu cầu in ấn tài liệu cho cá nhân, gia đình và văn phòng vừa & nhỏ.',
      quickSpecs: [
        'Máy in đơn năng',
        'RAM: 128MB | CPU: 600MHz',
        'Tốc độ in: 22ppm (A4) / 23ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: High-speed USB 2.0',
        'Hộp mực tiêu chuẩn: PC-211KEV (1.600 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'Máy in đơn năng' },
        { label: 'Tốc độ in', value: '22ppm (A4) / 23ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '128MB' },
        { label: 'Bộ xử lý CPU', value: '600MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0' },
        { label: 'Hộp mực đi kèm/tiêu chuẩn', value: 'PC-211KEV (1.600 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Laser Pantum P2505W',
      slug: 'may-in-laser-pantum-p2505w',
      sku: 'PANTUM-P2505W',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in Laser đen trắng Pantum P2505W kết nối Wi-Fi không dây hiện đại, hỗ trợ in ấn từ điện thoại di động và máy tính bảng linh hoạt.',
      quickSpecs: [
        'Máy in đơn năng - In di động WIFI',
        'RAM: 128MB | CPU: 600MHz',
        'Tốc độ in: 22ppm (A4) / 23ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: High-speed USB, Wi-Fi',
        'Hộp mực tiêu chuẩn: PC-211KEV (1.600 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'Máy in đơn năng, in không dây Wi-Fi' },
        { label: 'Tốc độ in', value: '22ppm (A4) / 23ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '128MB' },
        { label: 'Bộ xử lý CPU', value: '600MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0, Wi-Fi 802.11b/g/n' },
        { label: 'Hộp mực đi kèm/tiêu chuẩn', value: 'PC-211KEV (1.600 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Laser Pantum P3022D',
      slug: 'may-in-laser-pantum-p3022d',
      sku: 'PANTUM-P3022D',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in Laser Pantum P3022D trang bị tính năng in hai mặt tự động đảo bản in, tốc độ 30 trang/phút, đi kèm hộp mực dung lượng lớn 3.000 trang.',
      quickSpecs: [
        'Máy in đơn năng - In 2 mặt tự động',
        'RAM: 32MB | CPU: 500MHz',
        'Tốc độ in: 30ppm (A4) / 32ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: High-speed USB',
        'Hộp mực theo máy: TL-412HR (3.000 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'Máy in đơn năng, In 2 mặt tự động' },
        { label: 'Tốc độ in', value: '30ppm (A4) / 32ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '32MB' },
        { label: 'Bộ xử lý CPU', value: '500MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0' },
        { label: 'Hộp mực theo máy', value: 'TL-412HR (3.000 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Laser Pantum P3010DW',
      slug: 'may-in-laser-pantum-p3010dw',
      sku: 'PANTUM-P3010DW',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in Laser Pantum P3010DW in hai mặt tự động đảo bản in, hỗ trợ đầy đủ kết nối Wi-Fi di động và mạng LAN nội bộ.',
      quickSpecs: [
        'Máy in đơn năng - In 2 mặt tự động + Wi-Fi',
        'RAM: 128MB | CPU: 350MHz',
        'Tốc độ in: 30ppm (A4) / 32ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: High-speed USB, Wi-Fi, LAN',
        'Hộp mực tiêu chuẩn: TL-412HR (3.000 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'Máy in đơn năng, In 2 mặt tự động, Wi-Fi, LAN' },
        { label: 'Tốc độ in', value: '30ppm (A4) / 32ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '128MB' },
        { label: 'Bộ xử lý CPU', value: '350MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0, Ethernet (LAN), Wi-Fi' },
        { label: 'Hộp mực tiêu chuẩn', value: 'TL-412HR (3.000 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Laser Pantum P3308DW',
      slug: 'may-in-laser-pantum-p3308dw',
      sku: 'PANTUM-P3308DW',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in Laser Pantum P3308DW công suất cao, tốc độ in 33-35 trang/phút, bộ nhớ RAM 256MB, in 2 mặt tự động cùng kết nối mạng dây & Wi-Fi.',
      quickSpecs: [
        'Máy in đơn năng - In 2 mặt tự động + Wi-Fi',
        'RAM: 256MB | CPU: 350MHz',
        'Tốc độ in: 33ppm (A4) / 35ppm (Letter)',
        'Trang đầu in ≤ 8.2 giây',
        'Kết nối: High-speed USB, Wi-Fi, LAN',
        'Hộp mực tiêu chuẩn: TL-412HR (3.000 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'Máy in đơn năng, In 2 mặt tự động, Wi-Fi, LAN' },
        { label: 'Tốc độ in', value: '33ppm (A4) / 35ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 8.2 giây' },
        { label: 'Bộ nhớ RAM', value: '256MB' },
        { label: 'Bộ xử lý CPU', value: '350MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0, Ethernet (LAN), Wi-Fi' },
        { label: 'Hộp mực tiêu chuẩn', value: 'TL-412HR (3.000 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Laser Pantum BP5100DN',
      slug: 'may-in-laser-pantum-bp5100dn',
      sku: 'PANTUM-BP5100DN',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in Laser tốc độ cao Pantum BP5100DN dành riêng cho văn phòng lớn, tốc độ vượt trội 40 trang/phút, CPU 1.2GHz, bộ nhớ 512MB.',
      quickSpecs: [
        'Máy in đơn năng - In 2 mặt tự động + Mạng LAN',
        'RAM: 512MB | CPU: 1.2GHz',
        'Tốc độ in: 40ppm (A4) / 42ppm (Letter)',
        'Trang đầu in ≤ 6.9 giây',
        'Kết nối: Hi-Speed USB 2.0, Ethernet LAN',
        'Hộp mực tiêu chuẩn: TL-5120 (3.000 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'Máy in đơn năng công suất lớn, In 2 mặt tự động, Mạng LAN' },
        { label: 'Tốc độ in', value: '40ppm (A4) / 42ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 6.9 giây' },
        { label: 'Bộ nhớ RAM', value: '512MB' },
        { label: 'Bộ xử lý CPU', value: '1.2GHz' },
        { label: 'Cổng kết nối', value: 'Hi-Speed USB 2.0, Ethernet LAN' },
        { label: 'Hộp mực tiêu chuẩn', value: 'TL-5120 (3.000 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Đa năng Pantum BM2310AW',
      slug: 'may-in-da-nang-pantum-bm2310aw',
      sku: 'PANTUM-BM2310AW',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in Laser đa chức năng Pantum BM2310AW tích hợp khay nạp tài liệu tự động ADF, kết nối Wi-Fi & LAN tiện dụng cho văn phòng làm việc hiện đại.',
      quickSpecs: [
        'Máy in đa năng - Khay ADF + Wi-Fi',
        'RAM: 256MB | CPU: 800MHz',
        'Tốc độ in: 22ppm (A4) / 23ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: Hi-speed USB, Wi-Fi, LAN',
        'Hộp mực tiêu chuẩn: TO-C2310H (1.600 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'In, Copy, Scan đa năng, khay ADF tự động' },
        { label: 'Tốc độ in', value: '22ppm (A4) / 23ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '256MB' },
        { label: 'Bộ xử lý CPU', value: '800MHz' },
        { label: 'Cổng kết nối', value: 'Hi-speed USB 2.0, Wi-Fi, LAN' },
        { label: 'Hộp mực tiêu chuẩn', value: 'TO-C2310H (1.600 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Đa năng Pantum M6558',
      slug: 'may-in-da-nang-pantum-m6558',
      sku: 'PANTUM-M6558',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in đa chức năng Pantum M6558 trang bị khay tự động ADF giúp photocopy và quét nhiều trang tài liệu nhanh chóng.',
      quickSpecs: [
        'Máy in đa năng - Khay nạp ADF',
        'RAM: 128MB | CPU: 600MHz',
        'Tốc độ in: 22ppm (A4) / 23ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: High-speed USB 2.0',
        'Hộp mực tiêu chuẩn: PC-211KEV (1.600 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'In, Copy, Scan đa năng với khay ADF' },
        { label: 'Tốc độ in', value: '22ppm (A4) / 23ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '128MB' },
        { label: 'Bộ xử lý CPU', value: '600MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0' },
        { label: 'Hộp mực tiêu chuẩn', value: 'PC-211KEV (1.600 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Đa năng Pantum M6505NW',
      slug: 'may-in-da-nang-pantum-m6505nw',
      sku: 'PANTUM-M6505NW',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in đa chức năng Pantum M6505NW hỗ trợ in qua mạng dây LAN và mạng không dây Wi-Fi, bản in sắc nét.',
      quickSpecs: [
        'Máy in đa năng - In qua mạng + Wi-Fi',
        'RAM: 128MB | CPU: 525MHz',
        'Tốc độ in: 22ppm (A4) / 23ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: High-speed USB, Wi-Fi, LAN',
        'Hộp mực tiêu chuẩn: PC-211KEV (1.600 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'In, Copy, Scan đa năng, kết nối mạng LAN & Wi-Fi' },
        { label: 'Tốc độ in', value: '22ppm (A4) / 23ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '128MB' },
        { label: 'Bộ xử lý CPU', value: '525MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0, Ethernet (LAN), Wi-Fi' },
        { label: 'Hộp mực tiêu chuẩn', value: 'PC-211KEV (1.600 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Đa năng Pantum M6505',
      slug: 'may-in-da-nang-pantum-m6505',
      sku: 'PANTUM-M6505',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in Laser đa chức năng Pantum M6505 (Print / Copy / Scan) thiết kế nhỏ gọn, dễ vận hành, phù hợp cho cá nhân và văn phòng vừa.',
      quickSpecs: [
        'Máy in đa năng (Print / Copy / Scan)',
        'RAM: 128MB | CPU: 525MHz',
        'Tốc độ in: 22ppm (A4) / 23ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: High-speed USB 2.0',
        'Hộp mực tiêu chuẩn: PC-211KEV (1.600 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'In, Copy, Scan đa năng' },
        { label: 'Tốc độ in', value: '22ppm (A4) / 23ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '128MB' },
        { label: 'Bộ xử lý CPU', value: '525MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0' },
        { label: 'Hộp mực tiêu chuẩn', value: 'PC-211KEV (1.600 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Đa năng Pantum M6702DW',
      slug: 'may-in-da-nang-pantum-m6702dw',
      sku: 'PANTUM-M6702DW',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in đa năng Pantum M6702DW in đảo mặt tự động, tốc độ 30 trang/phút, trang bị kết nối mạng Wi-Fi và Ethernet LAN.',
      quickSpecs: [
        'Máy in đa năng - In 2 mặt tự động + Wi-Fi',
        'RAM: 128MB | CPU: 525MHz',
        'Tốc độ in: 30ppm (A4) / 32ppm (Letter)',
        'Trang đầu in ≤ 7.8 giây',
        'Kết nối: High-speed USB, Wi-Fi, LAN',
        'Hộp mực tiêu chuẩn: TL-412HR (3.000 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'In, Copy, Scan đa năng, In 2 mặt tự động, Wi-Fi, LAN' },
        { label: 'Tốc độ in', value: '30ppm (A4) / 32ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 7.8 giây' },
        { label: 'Bộ nhớ RAM', value: '128MB' },
        { label: 'Bộ xử lý CPU', value: '525MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0, Ethernet (LAN), Wi-Fi' },
        { label: 'Hộp mực tiêu chuẩn', value: 'TL-412HR (3.000 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Đa năng Pantum M7108DW',
      slug: 'may-in-da-nang-pantum-m7108dw',
      sku: 'PANTUM-M7108DW',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in đa năng Pantum M7108DW mạnh mẽ với khay tự động ADF, in đảo 2 mặt tự động, tốc độ 33 trang/phút, kết nối Wi-Fi & LAN.',
      quickSpecs: [
        'Máy in đa năng - ADF + In 2 mặt + Wi-Fi',
        'RAM: 256MB | CPU: 525MHz',
        'Tốc độ in: 33ppm (A4) / 35ppm (Letter)',
        'Trang đầu in ≤ 8.2 giây',
        'Kết nối: High-speed USB, Wi-Fi, LAN',
        'Hộp mực tiêu chuẩn: TL-412HR (3.000 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'In, Copy, Scan đa năng, khay ADF, In 2 mặt tự động, Wi-Fi, LAN' },
        { label: 'Tốc độ in', value: '33ppm (A4) / 35ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 8.2 giây' },
        { label: 'Bộ nhớ RAM', value: '256MB' },
        { label: 'Bộ xử lý CPU', value: '525MHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0, Ethernet (LAN), Wi-Fi' },
        { label: 'Hộp mực tiêu chuẩn', value: 'TL-412HR (3.000 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },
    {
      name: 'Máy in Đa năng Pantum BM5100ADN',
      slug: 'may-in-da-nang-pantum-bm5100adn',
      sku: 'PANTUM-BM5100ADN',
      categoryId: CATEGORY_MAY_IN,
      productType: 'standard',
      images: [defaultPrinterImage],
      description: 'Máy in đa năng chuyên nghiệp Pantum BM5100ADN tốc độ khủng 40 trang/phút, khay ADF tự động, in 2 mặt và kết nối mạng LAN doanh nghiệp.',
      quickSpecs: [
        'Máy in đa năng - ADF + In 2 mặt + Mạng LAN',
        'RAM: 512MB | CPU: 1.2GHz',
        'Tốc độ in: 40ppm (A4) / 42ppm (Letter)',
        'Trang đầu in ≤ 6.9 giây',
        'Kết nối: High-speed USB 2.0, LAN',
        'Hộp mực tiêu chuẩn: TL-5120 (3.000 Trang)',
      ],
      specifications: [
        { label: 'Chức năng', value: 'In, Copy, Scan đa năng, khay ADF tự động, In 2 mặt tự động, Mạng LAN' },
        { label: 'Tốc độ in', value: '40ppm (A4) / 42ppm (Letter)' },
        { label: 'Thời gian in trang đầu', value: '≤ 6.9 giây' },
        { label: 'Bộ nhớ RAM', value: '512MB' },
        { label: 'Bộ xử lý CPU', value: '1.2GHz' },
        { label: 'Cổng kết nối', value: 'High-speed USB 2.0, Ethernet (LAN)' },
        { label: 'Hộp mực tiêu chuẩn', value: 'TL-5120 (3.000 trang)' },
      ],
      price: 0,
      stockQuantity: 100,
    },

    // --------------------------------------------------------------------------
    // HỘP MỰC & CHAI MỰC NẠP PANTUM (Danh mục: Vật tư - ID 51)
    // --------------------------------------------------------------------------
    {
      name: 'Hộp mực Pantum TO-C2310H',
      slug: 'hop-muc-pantum-to-c2310h',
      sku: 'PANTUM-TO-C2310H',
      categoryId: CATEGORY_VAT_TU,
      productType: 'standard',
      images: [defaultSupplyImage],
      description: 'Hộp mực Laser đen chính hãng Pantum TO-C2310H dung lượng 1.600 trang, mang lại bản in sắc nét, bền màu và bảo vệ tuổi thọ máy in.',
      quickSpecs: [
        'Hộp mực in Laser Pantum chính hãng',
        'Dung tích / Số trang in: 1.600 trang',
        'Máy in tương thích: BP2310 / BP2310W / BP2310NW / BM2310 / BM2310W / BM2310NW / BM2310A / BM2310AW',
      ],
      specifications: [
        { label: 'Loại sản phẩm', value: 'Hộp mực in Laser đen' },
        { label: 'Dung tích / Trang in', value: '1.600 trang (độ phủ 5%)' },
        { label: 'Loại máy tương thích', value: 'BP2310 / BP2310W / BP2310NW / BM2310 / BM2310W / BM2310NW / BM2310A / BM2310AW' },
      ],
      price: 0,
      stockQuantity: 200,
    },
    {
      name: 'Hộp mực Pantum PC-211KEV',
      slug: 'hop-muc-pantum-pc-211kev',
      sku: 'PANTUM-PC-211KEV',
      categoryId: CATEGORY_VAT_TU,
      productType: 'standard',
      images: [defaultSupplyImage],
      description: 'Hộp mực in Laser Pantum PC-211KEV chính hãng dung lượng 1.600 trang, chất lượng in vượt trội, dễ dàng tháo lắp.',
      quickSpecs: [
        'Hộp mực in Laser Pantum chính hãng',
        'Dung tích / Số trang in: 1.600 trang (độ phủ 5%)',
        'Máy in thích hợp: P2200 / P2200W / P2516 / P2505W / M6505 / M6508 / M6508DW / M6558',
      ],
      specifications: [
        { label: 'Loại sản phẩm', value: 'Hộp mực in Laser đen' },
        { label: 'Dung tích / Trang in', value: '1.600 trang (độ phủ 5%)' },
        { label: 'Loại máy tương thích', value: 'P2200/P2200W/P2516/P2505W/M6505/M6508/M6508DW/M6558' },
      ],
      price: 0,
      stockQuantity: 200,
    },
    {
      name: 'Hộp mực Pantum TL-412HR',
      slug: 'hop-muc-pantum-tl-412hr',
      sku: 'PANTUM-TL-412HR',
      categoryId: CATEGORY_VAT_TU,
      productType: 'standard',
      images: [defaultSupplyImage],
      description: 'Hộp mực in Laser Pantum TL-412HR chính hãng dung lượng cao 3.000 trang bản in tiêu chuẩn, giúp tiết kiệm chi phí in ấn tối đa.',
      quickSpecs: [
        'Hộp mực in Laser Pantum chính hãng dung lượng cao',
        'Dung tích / Số trang in: 3.000 trang (độ phủ 5%)',
        'Máy in thích hợp: P3308DW / P3010D / P3010DW / P3012D / M6702DW / M6708D / M7108DW',
      ],
      specifications: [
        { label: 'Loại sản phẩm', value: 'Hộp mực in Laser đen dung lượng cao' },
        { label: 'Dung tích / Trang in', value: '3.000 trang (độ phủ 5%)' },
        { label: 'Loại máy tương thích', value: 'P3308DW/P3010D/P3010DW/P3012D/M6702DW/M6708D/M7108DW' },
      ],
      price: 0,
      stockQuantity: 200,
    },
    {
      name: 'Hộp mực Pantum TL-A5220',
      slug: 'hop-muc-pantum-tl-a5220',
      sku: 'PANTUM-TL-A5220',
      categoryId: CATEGORY_VAT_TU,
      productType: 'standard',
      images: [defaultSupplyImage],
      description: 'Hộp mực in Laser Pantum TL-A5220 chính hãng dùng cho các dòng máy in và đa năng công suất lớn BP5200DN, BM5200ADN.',
      quickSpecs: [
        'Hộp mực in Laser Pantum chính hãng',
        'Dung tích / Số trang in: 3.000 trang (độ phủ 5%)',
        'Máy in thích hợp: BP5200DN / BP5200DW / BM5200ADN',
      ],
      specifications: [
        { label: 'Loại sản phẩm', value: 'Hộp mực in Laser đen' },
        { label: 'Dung tích / Trang in', value: '3.000 trang (độ phủ 5%)' },
        { label: 'Loại máy tương thích', value: 'BP5200DN/BP5200DW/BM5200ADN' },
      ],
      price: 0,
      stockQuantity: 200,
    },
    {
      name: 'Hộp mực Pantum TL-5120',
      slug: 'hop-muc-pantum-tl-5120',
      sku: 'PANTUM-TL-5120',
      categoryId: CATEGORY_VAT_TU,
      productType: 'standard',
      images: [defaultSupplyImage],
      description: 'Hộp mực in Laser Pantum TL-5120 chính hãng dung lượng 3.000 trang, chất lượng in nét đậm, chuẩn đẹp.',
      quickSpecs: [
        'Hộp mực in Laser Pantum chính hãng',
        'Dung tích / Số trang in: 3.000 trang (độ phủ 5%)',
        'Máy in thích hợp: BP5100DN / BP5100DW / BM5100ADN / BM5100ADW',
      ],
      specifications: [
        { label: 'Loại sản phẩm', value: 'Hộp mực in Laser đen' },
        { label: 'Dung tích / Trang in', value: '3.000 trang (độ phủ 5%)' },
        { label: 'Loại máy tương thích', value: 'BP5100DN/BP5100DW/BM5100ADN/BM5100ADW' },
      ],
      price: 0,
      stockQuantity: 200,
    },
    {
      name: 'Chai mực nạp Pantum TN-412H',
      slug: 'chai-muc-nap-pantum-tn-412h',
      sku: 'PANTUM-TN-412H',
      categoryId: CATEGORY_VAT_TU,
      productType: 'standard',
      images: [defaultSupplyImage],
      description: 'Chai mực bơm/nạp Pantum TN-412H chính hãng mực đen cao cấp, nạp mực dễ dàng, số trang in lên tới 3.000 trang.',
      quickSpecs: [
        'Chai mực nạp/bơm chính hãng Pantum',
        'Màu sắc: Đen (Black)',
        'Số trang in: 3.000 trang (độ phủ 5%)',
        'Máy in tương thích: P3022D / P3010DW / P3308DW / M6702DW / M7108DW...',
      ],
      specifications: [
        { label: 'Loại sản phẩm', value: 'Chai mực nạp / mực bơm' },
        { label: 'Màu sắc', value: 'Đen' },
        { label: 'Số trang in', value: '3.000 trang (độ phủ 5%)' },
        { label: 'Máy in tương thích', value: 'P3022D/P3010DW/P3308DW/M6702DW/M7108DW...' },
      ],
      price: 0,
      stockQuantity: 300,
    },
    {
      name: 'Chai mực nạp Pantum RG-208',
      slug: 'chai-muc-nap-pantum-rg-208',
      sku: 'PANTUM-RG-208',
      categoryId: CATEGORY_VAT_TU,
      productType: 'standard',
      images: [defaultSupplyImage],
      description: 'Chai mực bơm/nạp Pantum RG-208 chính hãng dành cho dòng máy in phổ thông Pantum P2500, M6500 series, dung lượng 1.600 trang.',
      quickSpecs: [
        'Chai mực nạp/bơm chính hãng Pantum',
        'Màu sắc: Đen (Black)',
        'Số trang in: 1.600 trang (độ phủ 5%)',
        'Máy in tương thích: P2505 / P2200 / P2516 / M6505 / M6558...',
      ],
      specifications: [
        { label: 'Loại sản phẩm', value: 'Chai mực nạp / mực bơm' },
        { label: 'Màu sắc', value: 'Đen' },
        { label: 'Số trang in', value: '1.600 trang (độ phủ 5%)' },
        { label: 'Máy in tương thích', value: 'P2505/P2200/P2516/M6505/M6558...' },
      ],
      price: 0,
      stockQuantity: 300,
    },
  ];

  let successCount = 0;

  for (const item of productsData) {
    // Upsert sản phẩm
    const product = await prisma.product.upsert({
      where: { slug: item.slug },
      update: {
        name: item.name,
        categoryId: item.categoryId,
        brandId: brand.id,
        brand: brand.name,
        images: item.images,
        description: item.description,
        productType: item.productType,
        quickSpecs: item.quickSpecs,
        specifications: item.specifications,
        isActive: true,
        metaTitle: `${item.name} Chính Hãng - Máy Văn Phòng Xanh`,
        metaDescription: item.description.substring(0, 160),
      },
      create: {
        name: item.name,
        slug: item.slug,
        categoryId: item.categoryId,
        brandId: brand.id,
        brand: brand.name,
        images: item.images,
        description: item.description,
        productType: item.productType,
        quickSpecs: item.quickSpecs,
        specifications: item.specifications,
        isActive: true,
        metaTitle: `${item.name} Chính Hãng - Máy Văn Phòng Xanh`,
        metaDescription: item.description.substring(0, 160),
      },
    });

    // Upsert biến thể sản phẩm (Variant)
    await prisma.productVariant.upsert({
      where: { sku: item.sku },
      update: {
        productId: product.id,
        name: 'Mặc định',
        price: item.price,
        stockQuantity: item.stockQuantity,
        images: item.images,
      },
      create: {
        productId: product.id,
        sku: item.sku,
        name: 'Mặc định',
        price: item.price,
        stockQuantity: item.stockQuantity,
        images: item.images,
      },
    });

    successCount++;
    console.log(`  [${successCount}/20] ✅ Đã lưu: ${item.name} (SKU: ${item.sku})`);
  }

  console.log(`\n🎉 Hoàn thành nhập hàng loạt thành công ${successCount}/20 sản phẩm Pantum!`);
}

main()
  .catch((e) => {
    console.error('❌ Lỗi khi nhập sản phẩm:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
